//===-- CCircPasses.td - CCirc transformation definition file -*- tablegen -*-===//

#ifndef DIALECT_INCLUDE_CCIRC_TRANSFORMS_CCIRC_PASSES_TD
#define DIALECT_INCLUDE_CCIRC_TRANSFORMS_CCIRC_PASSES_TD

include "mlir/Pass/PassBase.td"

//def DecomposeMultiControl : Pass<"decompose-multi-control"> {
//  let summary = "Efficiently decompose multli-controlled gates";
//  let constructor = "qcirc::createDecomposeMultiControlPass()";
//}

#endif // DIALECT_INCLUDE_CCIRC_TRANSFORMS_CCIRC_PASSES_TD

